### ISSUE TITLE
Fix stylize config to work with ALLOW_MULTILINE_LAMBDAS

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#1009]
Per https://github.com/RoboJackets/style-configs/pull/2.

It seems like yapf is formatting fine but stylize is throwing an error.

```
Traceback (most recent call last):
  File "/usr/local/bin/stylize", line 9, in <module>
    load_entry_point('stylize==0.3.1', 'console_scripts', 'stylize')()
  File "/usr/local/lib/python3.5/dist-packages/stylize/__main__.py", line 193, in main
    workers.map(process_file, files_to_format)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/stylize/__main__.py", line 174, in process_file
    ARGS, filepath, ARGS.check, create_patch)
  File "/usr/local/lib/python3.5/dist-packages/stylize/yapf_formatter.py", line 43, in run
    (filepath, err.decode('utf-8')))
RuntimeError: Call to yapf failed for file 'soccer/gameplay/visualization/__init__.py':
yapf: Unknown style option "ALLOW_MULTILINE_LAMBDAS"
```

**Comment by jgkamat** [comment]
This is caused by stylize pinning our `yapf` version to `0.6.0`. Multiline Lambdas were added in 0.7.0.
