### ISSUE TITLE
Add mypy to CI system

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#982]
Related to #972

MyPy is a program that does static type checking for python, but it is only useful once we begin using the proper annotations. This is a very long term issue, since mypy is not 'stable' yet. For example, it crashes when we run it with our code currently:

```
soccer/gameplay/timeout_behavior.py: error: Name '__builtins__' is not defined
soccer/gameplay/timeout_behavior.py:14: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/mypy", line 6, in <module>
    main(__file__)
  File "/usr/lib64/python3.4/site-packages/mypy/main.py", line 38, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/lib64/python3.4/site-packages/mypy/main.py", line 79, in type_check_only
    options=options)
  File "/usr/lib64/python3.4/site-packages/mypy/build.py", line 181, in build
    dispatch(sources, manager)
  File "/usr/lib64/python3.4/site-packages/mypy/build.py", line 1470, in dispatch
    process_graph(graph, manager)
  File "/usr/lib64/python3.4/site-packages/mypy/build.py", line 1650, in process_graph
    process_stale_scc(graph, scc)
  File "/usr/lib64/python3.4/site-packages/mypy/build.py", line 1721, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/lib64/python3.4/site-packages/mypy/build.py", line 1402, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 236, in visit_file
    self.accept(d)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 2556, in accept
    node.accept(self)
  File "/usr/lib64/python3.4/site-packages/mypy/nodes.py", line 690, in accept
    return visitor.visit_class_def(self)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 554, in visit_class_def
    self.analyze_base_classes(defn)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 784, in analyze_base_classes
    base_types.append(self.object_type())
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 854, in object_type
    return self.named_type('__builtins__.object')
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 867, in named_type
    sym = self.lookup_qualified(qualified_name, None)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 2377, in lookup_qualified
    n = self.lookup(parts[0], ctx)  # type: SymbolTableNode
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 2361, in lookup
    self.name_not_defined(name, ctx)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 2522, in name_not_defined
    self.fail(message, ctx)
  File "/usr/lib64/python3.4/site-packages/mypy/semanal.py", line 2535, in fail
    assert ctx is not None, msg
AssertionError: Name '__builtins__' is not defined
```

**Comment by jgkamat** [comment]
Actually the above error is me installing mypy incorrectly, the latest version is fine. This isn't so bad actually. I'll try and integrate it!
